---
- name: Download Reference Data
  include: refdata-download.yml
  when: refdata_download

- name: Install Ephemeris
  include: ephemeris-install.yml

- name: Let Galaxy be aware of reference data
  include: locs.yml
