---
- name: Download Reference Data
  include: refdata-download.yml
  when: refdata_download

- name: Get installed tools list
  include: get-installed-tools-list.yml

- name: Let Galaxy be aware of reference data
  include: locs.yml
