---
- name: Create/invoke script virtualenv
  pip: name={{ item }} virtualenv={{ galaxy_tools_base_dir }}/venv virtualenv_command="{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
  with_items:
    - ephemeris==0.4.0

- name: Get installed tool list
  command: '{{ galaxy_tool_base_dir }}/venv/bin/get_tool_list -g {{ galaxy_instance_url }} -o {{ galaxy_refdata_list_path}}/installed-tool-list.yml 


