---
# Create directories for reference data and logs

- name: Create log directory
  file: path={{ item }}
        state=directory
        owner={{ galaxy_user }}
        group={{ galaxy_user }}
  when_items:
    - '{{ refdata_log_path }}'
    - '{{ refdata_dir }}'
  become_user: root
  become_method: sudo
