---
# comment here

- include_vars: sacCer3-list.yml

- name: Create sacCer3 directory
  file: path={{ refdata_dir }}/sacCer3/{{ item.0.tool }}
        state=directory
        owner={{ galaxy_user }}
        group={{ galaxy_user }}
  with_subelements:
    - "{{ sacCer3 }}"
    - parts

- name: Download Reference Data
  get_url: url={{refdata_swift_storage_url}}/sacCer3/{{ item.0.tool }}/{{item.1.part}} dest={{refdata_dir}}/sacCer3/{{item.0.tool}}
  with_subelements:
    - "{{ sacCer3 }}"
    - parts
